apollo_rank: 16
apollo_scale: 32.0
apollo_target: all
apollo_update_interval: 200
badam_mode: layer
badam_switch_interval: 50
badam_switch_mode: ascending
badam_update_ratio: 0.05
bf16: true
create_new_adapter: false
cutoff_len: 2048
dataset: alpaca
dataset_dir: data
do_train: true
finetuning_type: lora
fp16: false
freeze_trainable_layers: 2
freeze_trainable_modules: all
galore_rank: 16
galore_scale: 2.0
galore_target: all
galore_update_interval: 200
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
mask_history: false
max_grad_norm: 1.0
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
num_train_epochs: 3.0
output_dir: output/test_run
packing: false
per_device_train_batch_size: 2
pissa_init: false
plot_loss: true
ppo_score_norm: false
ppo_whiten_rewards: false
pref_beta: 0.1
pref_ftx: 0.0
pref_loss: sigmoid
pure_bf16: false
quantization_method: bnb
report_to:
- none
resize_vocab: false
save_steps: 100
stage: sft
template: llama3
train_on_prompt: false
trust_remote_code: true
use_apollo: false
use_badam: false
use_cpu: false
use_dora: false
use_galore: false
use_rslora: false
val_size: 0.0
warmup_steps: 0
