services:
  llamafactory:
    build:
      dockerfile: ./docker/docker-cuda/Dockerfile
      context: ../..
      args:
        PIP_INDEX: https://pypi.org/simple
    container_name: llamafactory
    ports:
      - "7860:7860"
      - "8000:8000"
    volumes:
      - D:/llama/hf_cache:/root/.cache/huggingface
      - D:/llama/data:/app/shared_data
      - D:/llama/output:/app/output
    ipc: host
    tty: true
    stdin_open: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [ gpu ]
    restart: unless-stopped